name: Mac CI Check
on:
  push:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
    branches:
      - release-3.*
      - feature-3.*
      - master
  release:
    types: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_ubuntu:
    name: mac ci check
    runs-on: self-hosted-mac
    strategy:
      fail-fast: false
    env:
      DEPS_ROOT: ~/cache/deps
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false

      - name: brew install
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          echo "export PATH=/opt/homebrew/bin:$PATH" >> ~/.zshrc
          brew install ccache gmp lcov libomp automake pkg-config


      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-07-28
          override: true

      - name: Reuse build cache
        run: |
          mkdir -p ./build
          rm -rf deps
          ln -s ${{ env.DEPS_ROOT }} deps

      - name: Remove cache if correspond dir change
        run: ./tools/.ci/clear_build_cache.sh


      - name: Build for mac
        run: |
          mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=ON -DCOVERAGE=ON -DWITH_LIGHTNODE=ON -DWITH_CPPSDK=ON -DWITH_TIKV=OFF -DWITH_TARS_SERVICES=ON  .. || cat *.log
          cmake --build . --parallel 4

      - name: Test
        run: |
          cd build
          CTEST_OUTPUT_ON_FAILURE=TRUE make test